#Made by Bio Shot.
import os
from time import time
import winsound
import keyboard
import subprocess
import webbrowser
from time import sleep
typing = False

def delete(chars,speed):
    while chars > 0:
        keyboard.send("Backspace")
        sleep(speed)
        chars = chars - 1
subprocess.Popen("notepad")
sleep(1)
keyboard.write("Hello >:)", delay=0.1)
sleep(2)
delete(9,0.1)
sleep(2)
keyboard.write("You might be wondering...",delay=0.1)
delete(25,0.05)
sleep(3)
keyboard.write("who",delay=0.2)
delete(3,0.2)
sleep(1)
keyboard.write("am",delay=0.2)
delete(2,0.2)
sleep(1)
keyboard.write("I?",delay=0.3)
delete(2,0.2)
sleep(2)
keyboard.write("Well...", delay=0.2)
delete(7,0.2)
winsound.PlaySound("thinkingtheme.wav",winsound.SND_ASYNC)
sleep(1)
keyboard.write("Im In your computer :>",delay=0.1)
sleep(1)
delete(22,0.1)
keyboard.write("But, How did i get here?",delay=0.1)
sleep(1)
delete(24,0.1)
keyboard.write("Well, the answer is very very simple.",delay=0.1)
sleep(2)
delete(37,0.1)
keyboard.write("The Answer is...",delay=0.1)
delete(16,0.1)
keyboard.write("Y O U!",delay=0.1)
delete(6,0.1)
keyboard.write("I Know a lot about you, jordan.",delay=0.1)
sleep(1)
delete(31,0.1)
keyboard.write("I know your name is jordan and you like Jojo.",delay=0.1)
sleep(1)
delete(45,0.1)
keyboard.write("THAT ONLY MEANS ONE THING!")
sleep(1)
delete(26,0.1)
keyboard.write("ZA WORLDO!!!",delay=0.1)
winsound.PlaySound("ZAWORLDO",winsound.SND_ALIAS)
delete(13,0.1)
#winsound.PlaySound("thinkingtheme.wav",winsound.SND_ASYNC)
sleep(1)
keyboard.write("I can search the internet for things like that.",delay=0.1)
sleep(1)
delete(47,0.1)
keyboard.write("I can even open the internet >:)",delay=0.1)
sleep(0.1)
os.system("taskkill /f /im Notepad.exe")
webbrowser.open("https://www.bing.com/search?q=I+HAVE+OPENED+THE+INTERNET!&cvid=f8acfe7e30c74e53a02dbf35db00fe1f&aqs=edge..69i57j69i64.10108j0j1&pglt=299&FORM=ANNTA1&PC=U531&adlt=strict")
subprocess.Popen("Notepad.exe")
sleep(0.1)
keyboard.write("hmmm oh minecraft worlds, wonder what would happen if they got deleted >:)")
sleep(1)
os.system("taskkill /f /im Notepad.exe")
subprocess.Popen("pranked.bat")
